services:
  - type: web
    name: collabo-backend
    env: python
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn influencer_platform.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
